# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Vagrant box found by https://atlas.hashicorp.com/search
  # Vagrant provider used is VirtualBox.
  config.vm.box = "magmadigital/centos-7.0"

  # Disable automatic box update checking.
  # config.vm.box_check_update = false
  
  config.vm.hostname = "app"

  config.vm.provider "virtualbox" do |node|
    node.name = "flask"
  end 

  # Forces autogenerated Ansible inventory file to create
  # a host named "flask"
  config.vm.define "flask" do |i|
  end

  # Allow flask app connection from VirtualBox host. 
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Enable provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    # Enable for debugging Ansible playbooks.
    ansible.verbose  = "vvv"
    ansible.sudo     = true
  end
end
